### ISSUE TITLE
Scrape the people who who's viewed your profile

### ISSUE THREAD

**Issue by nevo-david** [linvo-io/linvo-scraper#12]
https://www.linkedin.com/analytics/profile-views/

**Comment by radhika2503** [comment]
hey 
please assign me this task and please brief me as this is my first hackoberfest.

**Comment by nevo-david** [comment]
@radhika2503 have you worked with scrapers before?

**Comment by radhika2503** [comment]
No

**Comment by Arjun31415** [comment]
I would like to work on this. I have worked with Selenium in python for web scraping before

**Comment by nevo-david** [comment]
Assigning it to you @Arjun31415 :)

**Comment by Arjun31415** [comment]
Ok so where can I ask questions If I am unsure of something

**Comment by nevo-david** [comment]
You can open a discussion :)
https://github.com/linvo-io/linvo-scraper/discussions
