### ISSUE TITLE
Readme.md example code triggers error

### ISSUE THREAD

**Issue by TheOtherBrian1** [linvo-io/linvo-scraper#20]
### System Information:
- OS: Windows 11 Home
- Processor:  x64-based processor
- Node version: v16.15.1

### Issue
In the Readme.md, there is the following code:

```javascript
import * as LinvoScraper from 'linvo-scraper';
import * as puppeteer from 'puppeteer';

(async () => {
    const browser = await puppeteer.launch({
        headless: false
    });
    const page = (await browser.newPage());
    const cdp = await page.target().createCDPSession();

    // that's the res Linvo is working in production
    await page.setViewport({
        width: 1440,
        height: 900,
    });

    // add ghost-cursor for maximum safety
    await LinvoScraper.tools.loadCursor(page, true);

    // Login with Linkedin
    const {token} = await LinvoScraper.services.login.process(page, cdp, {
        user: 'bang@linvo.io',
        password: 'superStrongPass!!%'
    })

    // set cookies
    await page.setCookie({
        name: "li_at",
        value: token,
        httpOnly: true,
        secure: true,
        sameSite: "None",
        priority: "Medium",
        path: "/",
        domain: ".www.linkedin.com",
    });
   //BELOW FUNCTION TRIGGERS ERROR
    await LinvoScraper.services.connect.process(page, cdp, {
        message: 'Hi Nevo! Let\'s connect!',
        url: 'https://www.linkedin.com/in/nevo-david/'
    })
})();
```

### Code block that triggers error (line 38):
```javascript
   //BELOW FUNCTION TRIGGERS ERROR
    await LinvoScraper.services.connect.process(page, cdp, {
        message: 'Hi Nevo! Let\'s connect!',
        url: 'https://www.linkedin.com/in/nevo-david/'
    })
```

### Error Message

> const gotSelector = "[Got Selector]".cyan() + " " + selector.blue();
> TypeError: "[Got Selector]".cyan is not a function

**Comment by nevo-david** [comment]
Are you sure you have the last version? we have uploaded a fix for it

**Comment by TheOtherBrian1** [comment]
Just downloaded the newest version. The bug has been fixed. Thanks. 
While I am here, there is another issue I am having. The library provides a scraper function in the [linvo-scraper](https://github.com/linvo-io/linvo-scraper/blob/main/lib/linkedin/linkedin.global.page.service.ts) file. It requires the following data: 

```javascript
interface RequiredData {
  page: number;
  url: string; //What URL?
  remove_overlapping: boolean;
}
```
The scraper isn't designed for all LinkedIn webpage. Which URLs work? It might be helpful to add URL types. I could add them if needed, but I would need to know which LinkedIn pages are scrapable.

**Comment by nevo-david** [comment]
it goes into the global search, you can either pass the sales nav search URL of normal Linkedn

**Comment by TheOtherBrian1** [comment]
I have been trying with the standard URL, but I receive a "Cannot navigate to invalid URL" error. Would it be possible to provide a link to an example search url?

**Comment by Arjun31415** [comment]
> I have been trying with the standard URL, but I receive a "Cannot navigate to invalid URL" error. Would it be possible to provide a link to an example search url?

Could you open a new issue because it is not related to the current one
