### ISSUE TITLE
Hacktoberfest issues

### ISSUE THREAD

**Issue by RommelTJ** [linvo-io/linvo-scraper#4]
Hi, just stumbled into this repo from reddit and noticed it was tagged with the hacktoberfest tag. I saw there's an issue to add a contributing template. Is there any low-hanging fruit or feature requests that you might want people to contribute towards? I'm interesting in lending a hand.

**Comment by nevo-david** [comment]
Added some good issues @RommelTJ

**Comment by RommelTJ** [comment]
Thanks!
